name: Docker Image CI

on:
  push:
    branches: [ main ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myapp
    - name: Login to docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --user ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
